# Site settings
baseURL = "https://gogogonzo.be"
languageCode = "en-US"
title = "GO GO GONZO - Where Extraordinary Begins."
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = false

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 Go Go Gonzo"

[params]

  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/front.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Privacy"
        url = "privacy.html"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Shop"
        url = "https://tickets.gogogonzo.be"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "Contact"
        url = "contact"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Legal"

      [[params.links.list2.link]]
        text = "Privacy"
        url = "privacy"
        new_tab = false # new tab

      [[params.links.list2.link]]
        text = "Disclosure"
        url = "disclosure"

      [[params.links.list2.link]]
        text = "Impressum"
        url = "impressum"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Link One"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "#"

      [[params.links.list3.link]]
        text = "Disclosure"
        url = "disclosure"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
